"""bigbang

Revision ID: c1c1864bc7da
Revises: 
Create Date: 2024-06-22 21:18:09.160501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c1864bc7da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('str_display_name', sa.String(), nullable=False),
    sa.Column('str_product_name', sa.String(), nullable=False),
    sa.Column('str_product_descrition', sa.String(), nullable=False),
    sa.Column('float_value_product', sa.String(), nullable=False),
    sa.Column('bool_available_product', sa.Boolean(), nullable=False),
    sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
    sa.Column('audit_created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_updated_on', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_user_login', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('str_display_name', sa.String(), nullable=False),
    sa.Column('str_username', sa.String(), nullable=False),
    sa.Column('str_password', sa.String(), nullable=False),
    sa.Column('str_email', sa.String(), nullable=False),
    sa.Column('audit_user_ip', sa.String(length=16), nullable=False),
    sa.Column('audit_created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_updated_on', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('audit_user_login', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email', 'user', ['str_email'], unique=True)
    op.create_index('idx_user_username', 'user', ['str_username'], unique=True)
    op.create_table('user_product_association',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_product_association')
    op.drop_index('idx_user_username', table_name='user')
    op.drop_index('idx_user_email', table_name='user')
    op.drop_table('user')
    op.drop_table('product')
    # ### end Alembic commands ###
